### ISSUE TITLE
ComboBox items are shown in wrong position when they are above ComboBox

### ISSUE THREAD

**Issue by PavelTurk** [mkpaz/atlantafx#101]
Run the following code:

```
public class JavaFxTest7 extends Application {

    @Override
    public void start(Stage stage) {
        Application.setUserAgentStylesheet(new Dracula().getUserAgentStylesheet());
        var items = FXCollections.observableArrayList(List.of("a", "b"));
        var combobox = new ComboBox<String>();
        combobox.setItems(items);

        var vBox = new VBox(combobox);
        vBox.setStyle("-fx-font-size: 15");
        vBox.setAlignment(Pos.BOTTOM_LEFT);

        Scene scene = new Scene(vBox, 600, 200);
        stage.setScene(scene);
        stage.show();
        stage.setMaximized(true);
    }

    public static void main(String[] args) {
        launch();
    }
}
```

And you will get this result:

![Peek 2024-05-23 12-42](https://github.com/mkpaz/atlantafx/assets/10261361/4ab9598b-e53a-4b4e-990d-2f63ed38b919)

As you see when you click it the fist time, then there is a space between the comboBox and items. The size of this space depends on the font size. At the same time, when you click the second time, then there is no such space.

When I use pure JavaFX (without atlantafx), then everything is OK:

![Peek 2024-05-23 12-41](https://github.com/mkpaz/atlantafx/assets/10261361/d5995b78-8d80-4b71-8c17-cdf5b82b3d5c)

**Comment by mkpaz** [comment]
It's a JavaFX bug. If it was AtlantaFX, the popup position will be wrong every time you open it.

```css
/* this reproduces same behavior with Modena*/
.combo-box-popup .list-cell {
    -fx-padding: 0 10 0 10;
}
```
