### ISSUE TITLE
Bug: ComboBox width is not equal to popup width.

### ISSUE THREAD

**Issue by PavelTurk** [mkpaz/atlantafx#105]
This is test code:
```
public class ComboBoxTest extends Application {

    @Override
    public void start(Stage primaryStage) {
        //Application.setUserAgentStylesheet(new Dracula().getUserAgentStylesheet()); //Line X
        var data = List.of(
                "foo",
                "foo loooooooooooooooooooooooooooong",
                "foo very looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong"
        );
        var comboBox1 = new ComboBox<>(FXCollections.observableArrayList(data));
        VBox root = new VBox(comboBox1);
        var scene = new Scene(root, 800, 200);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```
If you run this code as it is (without atlantafx) you will get this result:
![Peek 2024-08-02 10-47](https://github.com/user-attachments/assets/1545385c-93a0-4f35-80f9-efff51c925c7)

As you see when pure JavaFX is used then ComboBox width is equal to popup width. Now uncomment `Line X` to add atlantafx. You will get this result:

![Peek 2024-08-02 10-48](https://github.com/user-attachments/assets/d1275676-2415-4ec5-b734-33840396df9b). As you see this time ComboBox is less than popup width. So, if you click the longest item then ComboBox width will change making it "dancing" on the screen.

Could anyone say if there is a workaround for this problem (of course without setting the width of ComboBox manually)?

**Comment by mkpaz** [comment]
I don't see why they should be the same width. Add more letters and the popup will exceed the combobox width in Modena as well. Anyway, the calculation of the popup width is up to skin, not CSS.

![image](https://github.com/user-attachments/assets/fa200d57-1a92-442b-864a-636a22d8ebfa)
