### ISSUE TITLE
Is this project not maintained anymore?

### ISSUE THREAD

**Issue by PavelTurk** [mkpaz/atlantafx#106]
I see that there haven't been commits/ pull requests this year. I open issues and get no answer. Is this project not maintained anymore?

**Comment by mkpaz** [comment]
Yes, it's maintained. I consider the project stable, still use it in all my apps and haven't seen anything that can't be avoided. I'm busy with several other projects and have a little time to follow GitHub issues. The fact is that UI debugging requires **a lot of monkey testing** (multiplied by the number of themes).
