### ISSUE TITLE
How should I switch the font like in the example

### ISSUE THREAD

**Issue by iammmmmmm** [mkpaz/atlantafx#110]
I have read the source code of the example, and I believe that the method it uses to modify the font is unnecessarily complex for someone who only needs to make a single change. _**I am seeking a simpler and more efficient method to adjust the theme's font.**_
Thank you for your response.

**Comment by mkpaz** [comment]
AtlantaFX doesn't set a font family, so it defaults to your system font because that's how JavaFX works. However, it does set the [font size to 14px](https://github.com/mkpaz/atlantafx/blob/master/styles/src/settings/_config.scss#L7). You can change this via CSS on any node.
