### ISSUE TITLE
Tree and Table selection highlighting on lost focus

### ISSUE THREAD

**Issue by bykka** [mkpaz/atlantafx#15]
Both components Tree and Table do not highlight the selected element on losing focus.

I have implemented tables row editing as a popup dialog and when it has shown I do not see what exactly I'm trying to edit.

![11](https://user-images.githubusercontent.com/489997/194503136-389101de-071a-42d0-a02b-8fa3d6f20cff.gif)

**Comment by mkpaz** [comment]
Thanks for reporting this. I kinda missed that current rules only highlight selected for when control is focused. You can use [this rule](https://github.com/mkpaz/atlantafx/blob/master/styles/src/components/_data.scss#L80) without the `:focused` pseudo-class as a workaround. I will release new version with fix next week.

**Comment by mkpaz** [comment]
Fixed with https://github.com/mkpaz/atlantafx/commit/c77dec332f627cea46bfe2379951457c14a0f37f
