### ISSUE TITLE
Showing source code in the sampler breaks the transition animation

### ISSUE THREAD

**Issue by mikehearn** [mkpaz/atlantafx#16]
1. Select some different panes from the left hand. The content crossfades pleasingly.
2. View some source code.
3. Select some different panes. Now the source appears briefly during the fade.

**Comment by mkpaz** [comment]
Thanks! That's UI misbehaviour.

**Comment by mkpaz** [comment]
Fixed with https://github.com/mkpaz/atlantafx/commit/259ee6da61e8252cddcc32f3102bf19a82e53340
