### ISSUE TITLE
Very wide/tall combo box lists have broken rendering

### ISSUE THREAD

**Issue by mikehearn** [mkpaz/atlantafx#17]
If I select something from the wide/tall lists then only content outside the main content area renders, the rest is clipped. This isn't always reproducible. I'm on macOS.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/971089/194586185-db654c95-8b9e-40ca-8ecb-3da2bbf164d7.png">

**Comment by mikehearn** [comment]
Oh, nice. The screenshot tool captures correct screenshots, just on screen it was mis-rendered, ugh. Maybe it's a macOS bug?

**Comment by mkpaz** [comment]
I think this is it.

[JDK-8198497](https://bugs.openjdk.org/browse/JDK-8198497)

**Comment by mikehearn** [comment]
You're right, that's the issue exactly. Seems nobody ever investigated to
find out what causes it.

By the way, I was wondering if I could email you about something unrelated
to this bug? I'm doing a bit of market research and if you've got five
minutes it's be really helpful!

**Comment by mkpaz** [comment]
Sorry, for the late response.
I was sure email is in the profile.
