### ISSUE TITLE
Different input fields have slightly different border colors.

### ISSUE THREAD

**Issue by mimoguz** [mkpaz/atlantafx#21]
Examples use Nord Dark color theme.

![e1](https://user-images.githubusercontent.com/7283047/197384616-99a94012-0b36-4821-86bd-6e1b2b10a301.png)

More noticeable on an editable combo-box:

![e2](https://user-images.githubusercontent.com/7283047/197384726-9c8ec148-8b5d-4554-98f9-ed657bc2b2d5.png)

Using a color picker, arrow button border reads #5d6575, while text input border reads #6e7787.

**Comment by mkpaz** [comment]
Color is the same as well as border width. The difference is that spinner uses border color (stroke) while text inputs use background insets (two rectangles one on top of another). The latter is preferred option because of performance. Nor sure why I implemented spinner CSS this way, it needs some investigation.

**Comment by mimoguz** [comment]
Maybe that is the problem? The border color is semitransparent. Background insets approach is mixing the border color with container's background (unless you have an another rectangle under the border), while border color approach is mixing it with control's background.

**Comment by mimoguz** [comment]
I've delved into the code a bit today.  The issue with the editable combo-box was that both the combo-box itself and its text field had borders, so the border was drawn twice. Setting text-field border transparent solved it.

**Comment by mkpaz** [comment]
Thanks for investigating this! I think I'll also remove border opacity. At least from the Nord.
