### ISSUE TITLE
UseragentStylesheet required?

### ISSUE THREAD

**Issue by FlorianKirmaier** [mkpaz/atlantafx#25]
Small question,

does Atlantafx also work, when not setting the useragent stylesheet? Can it also work by only setting the stylesheet of the Scene?

I thought about adding an AtlantaFX Demo to the JPro Website, but changing the user agent stylesheet, would also affect the other demos.

**Comment by mkpaz** [comment]
Yes, it will work when added to the Scene stylesheets observable list. That in fact what Sampler [uses to provide hot reload](https://github.com/mkpaz/atlantafx/blob/master/sampler/src/main/java/atlantafx/sampler/theme/SamplerTheme.java#L28). But leaving platform UA stylesheet unchanged at the same time, means that Modena (or whatever default JavaFX theme for the target platform) styles will also be applied, so your controls will be styled from both AtlantaFX and Modena. As far as I know, it's possible to [override platform UA stylesheet](https://openjfx.io/javadoc/19/javafx.graphics/javafx/scene/Scene.html#setUserAgentStylesheet(java.lang.String)) for specific Scene, so you probably could try it that way.
