### ISSUE TITLE
What is the module name in  module-info?

### ISSUE THREAD

**Issue by eos1d3** [mkpaz/atlantafx#26]
I am using module-info but just cannot find atlantafx module name. Any help? Thanks!

**Comment by mkpaz** [comment]
It's `atlantafx.base` ([link](https://github.com/mkpaz/atlantafx/blob/master/base/src/main/java/module-info.java)). You should probably try to restart your IDE, invalidate project caches or something like that. I don't know what IDE your using, but Intellij quite often stucks on module name when adding new dependencies.

**Comment by eos1d3** [comment]
Thanks! I am using Eclipse and after restart, it works!
