### ISSUE TITLE
SceneBuilder theme support

### ISSUE THREAD

**Issue by ennerf** [mkpaz/atlantafx#27]
Using AtlantaFX with FXML/SceneBuilder is a bit annoying as there is no support for custom themes, and loading the theme as a separate css file on top of Modena behaves differently from loading it as an agent stylesheet. I didn't see a way to add themes without modifying the source code, but fortunately it's just [loading resources](https://github.com/gluonhq/scenebuilder/blob/256c360841f85da6c986963a82ef023e5bffd156/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java#L119-L134) that are simple to overwrite.

It's a bit of a hack, but below are some instructions in case anyone else like to use SceneBuilder. It might make sense to automate building the zip-file and/or try to get better support upstream once things are stable.

1. Download [atlantafx-scenebuilder-themes.zip](https://github.com/mkpaz/atlantafx/files/10023626/atlantafx-scenebuilder-themes.zip) to SceneBuilder's `$APPDIR` 
  (e.g. `%HOMEPATH%/Local/SceneBuilder/app/` on Windows)
2. open `$APPDIR/SceneBuilder.cfg` 
3. add `$APPDIR/atlantafx-scenebuilder-themes.zip` to the beginning of `app.classpath`

Resources in the zip get loaded first and overwrite the Caspian buttons with the 4 AtlantaFX themes

| SceneBuilder                | Caspian High Contrast (FX2) | AtlantaFX    |
|-----------------------------|-----------------------------|--------------|
| Caspian Embedded (FX2)      | no                          | Primer Light |
| Caspian Embedded (FX2)      | yes                         | Primer Dark  |
| Caspain Embedded QVGA (FX2) | no                          | Nord Light   |
| Caspian Embedded QVGA (FX2) | yes                         | Nord Dark    |

![image](https://user-images.githubusercontent.com/5491587/202213021-f467c7d8-25ce-4e1a-b20a-1c47939e676c.png)

**Comment by mkpaz** [comment]
I will pin this until Scene Builder support isn't delivered in some way.

**Comment by mkpaz** [comment]
Ok, I think it's implemented now. Should work with external themes as well. I also moved your explanation to the docs. Thanks again for finding the way to integrate AtlantaFX with SceneBuilder. Since I don't work with FXML I wouldn't do it myself.

**Comment by TelKel81** [comment]
Does this still work ? I tried multiple variations but no success.
e.g. :
[Application]
app.classpath=$APPDIR\AtlantaFX-2.1.0-scenebuilder-themes.zip:$APPDIR\scenebuilder-25.0.0-all.jar
app.mainclass=com.oracle.javafx.scenebuilder.app.SceneBuilderApp
app.classpath=$APPDIR\scenebuilder-25.0.0-SNAPSHOT-all.jar

[Application]
app.classpath=$APPDIR\AtlantaFX-2.1.0-scenebuilder-themes.zip:$APPDIR\scenebuilder-25.0.0-all.jar
app.mainclass=com.oracle.javafx.scenebuilder.app.SceneBuilderApp
app.classpath=$APPDIR\AtlantaFX-2.1.0-scenebuilder-themes.zip:$APPDIR\scenebuilder-25.0.0-SNAPSHOT-all.jar

Tried replacing ":" by ",", etc
Having a single app.classpath, nope

**Comment by ennerf** [comment]
Unfortunately, this no longer works with recent versions of SceneBuilder, and fixing it would require adding actual theming support. For now the only option is to use an older version.

https://github.com/mkpaz/atlantafx/issues/131

**Comment by CamilYed** [comment]
Could you provide the last SceneBuilder version which supports AtlantaFX theme

**Comment by ennerf** [comment]
I can confirm that [Scene Builder 23.0.1](https://github.com/gluonhq/scenebuilder/releases/tag/23.0.1) works
