### ISSUE TITLE
Sampler CSS broken, when starting from Maven/Mac

### ISSUE THREAD

**Issue by FlorianKirmaier** [mkpaz/atlantafx#30]
When I run with `mvn -pl sampler/pom.xml javafx:run`

It looks like the following:
<img width="1192" alt="Screenshot 2022-12-12 at 16 42 42" src="https://user-images.githubusercontent.com/6547435/207088645-2c6ed079-b046-450e-ac11-8db6b9b3bfa1.png">

Any Idea why?

When that's working, I would like to add AtlantaFX to the Sample Page of JPro.

**Comment by mkpaz** [comment]
Looks like CSS parser error. There should be some warnings in the Maven output....

**Comment by FlorianKirmaier** [comment]
Yes, i get an error, that the css doesn't exist.
```
Dec 13, 2022 1:55:11 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "/atlantafx/base/theme/primer-light.css" not found.
```

I've used the clean checkout of the project.
Now the question is, does it work for you, when you run it with the command `mvn -pl sampler/pom.xml javafx:run` ?

**Comment by FlorianKirmaier** [comment]
Hm, after doing `mvn clean install -DskipTests` it magically worked.

**Comment by mkpaz** [comment]
Interesting, I can't reproduce this.

```
> mvn -version
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /home/mkpaz/.sdkman/candidates/maven/current
Java version: 17.0.5, vendor: BellSoft, runtime: /home/mlinx/.sdkman/candidates/java/17.0.5-librca
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.0.11-200.fc36.x86_64", arch: "amd64", family: "unix"

> mvn clean
> mvn dependency:purge-local-repository -DmanualInclude="io.github.mkpaz" -DreResolve=false
> mvn -pl sampler/pom.xml javafx:run
```

I don't even have to build it locally, it downloads dependencies from Central.
