### ISSUE TITLE
Demo looks like it uses no antialiasing

### ISSUE THREAD

**Issue by crschnick** [mkpaz/atlantafx#35]
I just downloaded the demo and tried it out. The theme looks very good but the text looks like there is no antialiasing enabled. Does it have this enabled: https://openjfx.io/javadoc/17/javafx.graphics/javafx/scene/SceneAntialiasing.html ?

**Comment by mkpaz** [comment]
Yes, I noticed that too, but scene antialiasing has no effect to fonts. Well, at least I don't see the difference. The latter affected by [`-fx-font-smoothing-type`](https://github.com/mkpaz/atlantafx/blob/master/styles/src/general/_text.scss#L8). Seems like it's a [known problem](https://stackoverflow.com/a/24419312/5694145). I should probably change the value to `gray` for all themes. Thanks for reporting this.

**lcd**

![lcd](https://user-images.githubusercontent.com/25181998/218645661-cd12d225-b9d6-4396-a01d-5d622cd90d99.png)

**gray**

![gray](https://user-images.githubusercontent.com/25181998/218645700-34f61f0b-7f95-45a7-a62b-c8c7b2a71087.png)
