### ISSUE TITLE
Demo tooltip behavior is buggy

### ISSUE THREAD

**Issue by crschnick** [mkpaz/atlantafx#38]
When hovering the mouse over the `Position` -> `Top Left` element on the `Tooltip` page, the tooltip appears and hides in a loop.

**Comment by mkpaz** [comment]
Another JavaFX bug, I suppose. There is nothing specific in code sample. Did some tests, I see exactly the same behavior with default Modena theme. 

```java
public class Launcher extends Application {

    public static void main(String[] args) {
        launch();
    }

    @Override
    public void start(Stage stage) {
        var tooltip = new Tooltip("Test");
        tooltip.setAnchorLocation(PopupWindow.AnchorLocation.WINDOW_BOTTOM_RIGHT);

        var label = new Label("Hover Me");
        label.setTooltip(tooltip);
        label.setStyle("-fx-font-size: 5em;");

        var root = new StackPane();
        root.setAlignment(Pos.CENTER);
        root.getChildren().setAll(label);

        var scene = new Scene(root, 800, 600);
        stage.setScene(scene);
        stage.show();
    }
}
```

**Comment by crschnick** [comment]
Is there way in the demo application to disable all themes, i.e. to use the default JavaFX theme to easier test this?

**Comment by mkpaz** [comment]
No, because Modena uses it's own color system (looked-up color variables) and built on different UI/UX concepts. I don't think I could make it look decent with default UA stylesheet.
