### ISSUE TITLE
Add entry to JFXCentral

### ISSUE THREAD

**Issue by dlemmermann** [mkpaz/atlantafx#4]
This is a great looking stylesheet / custom controls. Would be fantastic if you could add an entry to jfx-central.com so that others will find it more easily. You can find the data repository for it here https://github.com/dlemmermann/jfxcentral-data

**Comment by mkpaz** [comment]
Thanks for the suggestion. I will do this after stable version get released.

**Comment by SamTV12345** [comment]
This project is awesome. Would be great to see that coming.

**Comment by dlemmermann** [comment]
Thank you for your addition!
