### ISSUE TITLE
SceneBuilder path

### ISSUE THREAD

**Issue by ennerf** [mkpaz/atlantafx#42]
I just saw the SceneBuilder integration. That's nice 👍 The current version is unfortunately broken on Windows and macOS because the directory structure does not match the expected `lib/app` directory. It'd probably also be good to have it intitialized to the standard installation path.

![image](https://user-images.githubusercontent.com/5491587/221209322-6f5f1dc6-a867-42ec-887b-738d58d276df.png)

I just checked multiple systems and the default installation looks like this:

**Windows**
```Java
var installDir = System.getProperty("user.home") + "/AppData/Local/SceneBuilder/";
var cfgDir =  installDir + "app/";
var cfgFile = cfgDir  + "SceneBuilder.cfg"
```

**macOS**
```Java
var installDir = "/Applications/SceneBuilder.app/";
var cfgDir =  installDir + "Contents/app/";
var cfgFile = cfgDir  + "SceneBuilder.cfg"
```

**Ubuntu**
```Java
var installDir = "/opt/scenebuilder/";
var cfgDir =  installDir + "lib/app/";
var cfgFile = cfgDir  + "SceneBuilder.cfg"
```

**Comment by mkpaz** [comment]
Ow. Yeah, that's jpackage app image format. It totally slipped my mind. Thanks for noticing.
