### ISSUE TITLE
Flat in Toolbar does not work

### ISSUE THREAD

**Issue by phamvanthanh** [mkpaz/atlantafx#44]
Hi,
Is this by design?
![image](https://user-images.githubusercontent.com/24784468/222090543-f1ff9d4f-c24f-4330-b984-faabb25df330.png)

**Comment by mkpaz** [comment]
Hello. Yes, toolbar uses flat styling for all buttons by default, no need to set it explicitly.

**Comment by phamvanthanh** [comment]
@mkpaz 
I am understanding that Flat means does not have a background by default state (not hover or selected, pressed). Am I wrong?

**Comment by mkpaz** [comment]
No, flat means no borders and elevation. Not the best name, I agree. Sometimes it's called `action` or `link` button.

**Comment by phamvanthanh** [comment]
Thanks
