### ISSUE TITLE
Tweak to remove horizonat scrollbar from TableView

### ISSUE THREAD

**Issue by parszab** [mkpaz/atlantafx#45]
Hi guys, thank you so much for AtlantaFX! A fantastic tool!

Would it be possible to add a css tweak to remove the scrollbar from TableView?

**Comment by mkpaz** [comment]
Hi. I thought about adding a tweak to hide table header, so it could be used as virtualized grid control, but hiding scrollbars should be possible too, yes.

**Comment by parszab** [comment]
> Hi. I thought about adding a tweak to hide table header, so it could be used as virtualized grid control, but hiding scrollbars should be possible too, yes.

That would also be very useful!

**Comment by mkpaz** [comment]
I this the issue is no longer relevant because JFX20 supports six [additional resize policies](https://openjfx.io/javadoc/20/javafx.controls/javafx/scene/control/TableView.html#CONSTRAINED_RESIZE_POLICY_ALL_COLUMNS) that prevent horizontal scrollbars from appearing.
