### ISSUE TITLE
Text highlight barely visible in Nord theme

### ISSUE THREAD

**Issue by parszab** [mkpaz/atlantafx#47]
Highlighting text in `TextField` or `TextArea` components is barely visible in Nord theme, especially in Dark mode. This is very visible even in the Sampler app. 

NB: This is also true for selection color in `ListView`, `TableView` etc components, most visibly in `striped` mode. I think it would be worth revisiting the global highlight color.

**Comment by mkpaz** [comment]
Nord lacks some contrast. That's ok, original theme doesn't have much contrast as well. But I see your point and keep this as a reminder.

**Comment by parszab** [comment]
I'm all for low contrast, but I think there is a more concrete issue here.

If you look at the screenshot below, the `ListView` has a correct contrast highlight on the selected item. But in the `TextField` where the cursor is I selected the word `StockFish` and there is no real way of saying what is selected. I think it should have the same selection color as the `ListView`.

![d2_nord](https://user-images.githubusercontent.com/15095671/225277452-9dd78609-b36c-4ef8-8e1d-ea83aea2fce8.png)

For reference here is a screenshot of the Emacs Nord theme which also contrasts selection a but more.

![emacs_nord](https://user-images.githubusercontent.com/15095671/225277380-ff4952cb-dc22-448a-abb6-24058a36defc.png)
