### ISSUE TITLE
Modal pane does not have a lot of contrast in dark themes

### ISSUE THREAD

**Issue by crschnick** [mkpaz/atlantafx#53]
So I tried using the ModalPane and it works great so far. However, I find that when using dark themes, the modal pane does not stand out as much as when using a light theme. Maybe the background can be made even darker in dark themes?

**Comment by mkpaz** [comment]
Yes, you're probably right. It also can be styled via [`-color-modal-pane-overlay`](https://github.com/mkpaz/atlantafx/blob/master/styles/src/components/_modal-pane.scss) variable. I think increasing opacity a bit should fix that.
