### ISSUE TITLE
Scene Builder integration not working

### ISSUE THREAD

**Issue by provision95** [mkpaz/atlantafx#54]
First of all Thank You from the bottom of my heart for this beautiful app. Today I tried to integrate AtlantaFX into Scene Builder, all went smooth, but the Builder is not starting after this operation:(

**Scene Builder Version 20**
**AtlantaFX Version 2.0.0**

I understand that it is a problem on Scene Builder side, but just wanted to let You know that it is not working with the latest Scene Builder.

Have a nice day:)

**Comment by mkpaz** [comment]
> I understand that it is a problem on Scene Builder side

Hey, thanks for reporting! Maybe it's not. Could you please share additional information, such as what OS you're using, the contents of the 'SceneBuilder.cfg' file located in the SceneBuilder [installation directory](https://docs.oracle.com/en/java/javase/20/jpackage/packaging-overview.html#GUID-DAE6A497-6E6F-4895-90CA-3C71AF052271), and a list of files in this directory?

You can also find manual installation instructions in [the doc](https://mkpaz.github.io/atlantafx/fxml/). The SceneBuilder theme pack can be downloaded from the releases page.

**Comment by provision95** [comment]
Sure!

**OS: Win11 / Intel 10 gen**
**JDK: 8 / 17**

I tried manual installation but it did not work too:(

![image](https://github.com/mkpaz/atlantafx/assets/43195550/d6379a72-bea5-4655-9aff-70faa389aa3e)

**Note: I removed a library addition prefix from the second class path setting, by doing this I can start scene builder, but caspian(prime-white) does not work**

**Comment by mkpaz** [comment]
Ok, got it. The classpath separator is ";" on Windows. Please, try this:

```
app.mainclass=$APPDIR/atlantafx-scene-builder.zip;$APPDIR/scenebuilder-20.0.0-all.jar
```

**Comment by provision95** [comment]
Yup, now it is working, thank You very much:)))
