### ISSUE TITLE
NotificationSkin

### ISSUE THREAD

**Issue by lwdillon** [mkpaz/atlantafx#56]
The maximum width of NotificationSkin's messageText is currently: messagetext.setmaxWidth (Region.USE_PREF_SIZE);
It should be set to messageText.setMaxWidth(Double.MAX_VALUE);

**Comment by mkpaz** [comment]
Maybe. It was necessary for correct text wrapping. In the final skin implementation, I'm not sure if it still is, so it should be tested. But why change it anyway? Is something not working for you?

**Comment by lwdillon** [comment]
当文本很少时，不会自动拉伸，请看图片。

![1686203873950](https://github.com/mkpaz/atlantafx/assets/14171008/3b4db7d1-5079-41cd-bab0-293b66ff6a7b)

**Comment by mkpaz** [comment]
Yes, I can confirm that. Thanks!
