### ISSUE TITLE
Popover does not take dark theme

### ISSUE THREAD

**Issue by vdjurovic** [mkpaz/atlantafx#64]
When using `NordDark` theme, popover does not use dark theme. It looks like background remains white, making text and controls look broken.

This is sample screenshot for dark theme:
![dark-theme-test](https://github.com/mkpaz/atlantafx/assets/5014293/ebdc71df-8395-40ec-82a9-b38dfc50949c)

For light theme, it looks OK:
![light-theme-test](https://github.com/mkpaz/atlantafx/assets/5014293/30247bef-05d0-4ce0-afa4-6e2352a4a594)

This is the sample code I used:

```
public class TestApp extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        var bp = new BorderPane();
        var hbox = new HBox();
        hbox.getChildren().add(new Label("Label"));
        hbox.getChildren().add(new TextField());
        var popup = new PopOver(hbox);
        popup.setArrowLocation(PopOver.ArrowLocation.TOP_CENTER);
        var button = new Button("Click me");
        button.setOnAction(e -> popup.show(button));

        bp.setCenter(button);
        Application.setUserAgentStylesheet(new NordDark().getUserAgentStylesheet());
        stage.setTitle("Dark theme test");
        var scene = new Scene(bp, 600, 400.0);
        stage.setScene(scene);
        stage.show();
    }
}
```

Is there something I'm missing in this code? Because in sampler app this works fine.
I'm running this on Kubuntu with Java 19 and JavaFX 19.0.2.1. In additon, this happens for all dark themes, not just `NordDark`.

**Comment by mkpaz** [comment]
I guess you're using ControlsFx because AtlantaFX control is [`Popover`](https://github.com/mkpaz/atlantafx/blob/master/base/src/main/java/atlantafx/base/controls/Popover.java), not [`PopOver`](https://github.com/controlsfx/controlsfx/blob/master/controlsfx/src/main/java/org/controlsfx/control/PopOver.java#L85).

**Comment by vdjurovic** [comment]
You're right, that was the exact problem. Thanks!
