### ISSUE TITLE
ComboBox popup location is not correct for the first time

### ISSUE THREAD

**Issue by wait-for-the-dawn** [mkpaz/atlantafx#67]
Thanks for the great project, I love this project very much!

ComboBox popup is not showing in the correct location for the first time, please see my scrrenshot below, there was a big gap between ComboBox selector and the popup.
![image](https://github.com/mkpaz/atlantafx/assets/139092850/7635f513-1896-4995-8b85-b6d638922f90)
When I clicked the selector for the second time, it just show in the correct location.
![image](https://github.com/mkpaz/atlantafx/assets/139092850/95520e6c-c15c-4ed0-a709-2faa5cc1df70)

Updated
It seems that this issue only occurred when there's not enough space at the bottom of the window, and it will pop up to the top of the CombBox, it also occurred for the first time show.
![image](https://github.com/mkpaz/atlantafx/assets/139092850/536b6b8a-a65d-479d-86f6-5c6e0be08df8)

**Comment by mkpaz** [comment]
Sorry, but it looks like JavaFX bug to me. There're many like this one [JDK-8170972](https://bugs.openjdk.org/browse/JDK-8170972), [JDK-8146180](https://bugs.openjdk.org/browse/JDK-8146180). Could you please check it with default Modena theme?

**Comment by wait-for-the-dawn** [comment]
This is a JavaFX bug, I can reproduce it with Modena theme. Unfortunately, this haven't been fixed with OpenJFX 17.0.7, and it seems this was not fixed with OpenJFX 21-ea+24 either.

Please close this issue as it was not AtlantaFX bug, sorry for the inconvenience.
