### ISSUE TITLE
Could the next releases use regular version numbers?

### ISSUE THREAD

**Issue by mikehearn** [mkpaz/atlantafx#7]
Heya,

I totally understand that AtlantaFX is in an early development phase, but versions like `0.1-SNAPSHOT2` aren't compatible with most packaging systems. As you can see, in `conveyor.conf` I had to override the version number to avoid that issue. If you could do releases with versions that consist purely of numbers (`0.1`, `0.2` etc) then that'd be appreciated and make things easier.

**Comment by mkpaz** [comment]
Absolutely. It follows [semantic versioning](https://semver.org/). I only release snapshots to give a quick preview for those who don't want to compile the project manually. They're kinda like nightly builds and not meant to be published anywhere else.

**Comment by mipastgt** [comment]
Even worse, on Mac the packager does not like version numbers which start with 0.

**Comment by mikehearn** [comment]
Thanks! 

The quality seems to be a fair bit higher than you're admitting to, it doesn't feel like alpha/nightly quality stuff, but that's no problem - the snapshot releases can still be advertised as however stable you feel they are, e.g. in the sampler app itself. It's just nice to let users easily try out the theme and have it self update. The `0.` prefix rule isn't a macOS restriction and doesn't apply to Conveyor, so maybe it's a jpackage thing.

**Comment by mipastgt** [comment]
Yes, I was referring to jpackage. I just stumbled over it when I tried to build AtlantaFX myself today.

**Comment by mkpaz** [comment]
I think it's no problem to start with `1.x.x` if it's a target platform requirement. Versioning numbering is a very subjective thing anyway that differs from project to project.

**Comment by mkpaz** [comment]
First stable version released.

**Comment by mikehearn** [comment]
Congrats! Sampler download is updated.

**Comment by mkpaz** [comment]
Thanks for the update!
