### ISSUE TITLE
DatePicker style issues

### ISSUE THREAD

**Issue by barmat80** [mkpaz/atlantafx#70]
Using all themes, DatePicker always renders quite different from AtlantaFX Sampler, but I can't understand why,

![datepicker](https://github.com/mkpaz/atlantafx/assets/10819014/d2a04848-b353-4ef2-8f7e-fb847bf0d86d)

Below my code (partially copied from the Sampler):

```
var today = LocalDate.now(ZoneId.systemDefault());
var datePicker = new DatePicker(today);
datePicker.setEditable(false);
datePicker.setPrefWidth(200);

var vbox = new VBox();
vbox.getChildren().add(datePicker);

var scene = new Scene(vbox, 300, 300);
scene.getStylesheets().add(Main.class.getResource("css/nord-light.css").toExternalForm());
primaryStage.setScene(scene);
```
Am I missing something or doing something wrong?

PS: Something similar happens also with TableView...

**Comment by mkpaz** [comment]
You haven't set up the theme properly, so your nodes are receiving styles from both Modena and AtlantaFX.

```java
scene.getStylesheets().add(Main.class.getResource("css/nord-light.css").toExternalForm());
```

You should use the `setUserAgentStylesheet()` method exactly as specified on the front page.

```java
Application.setUserAgentStylesheet(new PrimerLight().getUserAgentStylesheet());
// or
Application.setUserAgentStylesheet(/* path to the CSS file */);
```
