### ISSUE TITLE
TileSkinBase title ChangeListener code is wrong

### ISSUE THREAD

**Issue by qq528** [mkpaz/atlantafx#74]
`
 control.pseudoClassStateChanged(HAS_TITLE, control.getTitle() != null);
        registerChangeListener(control.titleProperty(), o -> {

            var value = getSkinnable().getDescription();// wrong

            titleLbl.setText(value);
            titleLbl.setVisible(value != null);
            titleLbl.setManaged(value != null);
            getSkinnable().pseudoClassStateChanged(HAS_TITLE, value != null);
        });

`

**Comment by Patresss** [comment]
Yep, it's a blocker for me: I can't set an internationalized string
