### ISSUE TITLE
Icon-only Button, ToggleButton and MenuButton have different sizes?

### ISSUE THREAD

**Issue by sillydan1** [mkpaz/atlantafx#85]
I am trying to have a toolbar with a mix of togglebuttons, menubuttons and regular buttons, but they all have slightly different sizes. Is this a bug, or am I doing something wrong?

Screenshots:

<img width="822" alt="Screenshot 2024-02-10 at 10 35 03" src="https://github.com/mkpaz/atlantafx/assets/4085393/c860022f-bf76-482a-82c3-64910be31f99">
<img width="822" alt="Screenshot 2024-02-10 at 10 34 45" src="https://github.com/mkpaz/atlantafx/assets/4085393/e1ad4762-56d1-4ca8-a010-5bdaa5a9cdfc">
<img width="822" alt="Screenshot 2024-02-10 at 10 34 36" src="https://github.com/mkpaz/atlantafx/assets/4085393/89e87f86-5834-445b-b931-e369474d7346">

Example code:
```java
var showHiddenFilesButton = new ToggleButton(null, new FontIcon(BootstrapIcons.EYE));
showHiddenFilesButton.getStyleClass().addAll(Styles.BUTTON_ICON);
showHiddenFilesButton.selectedProperty().set(showHiddenFiles.get());
showHiddenFiles.bind(showHiddenFilesButton.selectedProperty());
var showHiddenFilesTip = new Tooltip("This is a ToggleButton with styleClass().addAll(Styles.BUTTON_ICON)");
showHiddenFilesTip.setAnchorLocation(AnchorLocation.WINDOW_TOP_LEFT);
showHiddenFilesButton.setTooltip(showHiddenFilesTip);

var manualRefreshButton = new Button(null, new FontIcon(BootstrapIcons.ARROW_CLOCKWISE));
manualRefreshButton.getStyleClass().addAll(Styles.BUTTON_ICON);
var refreshTip = new Tooltip("This is a Button with styleClass().addAll(Styles.BUTTON_ICON)");
refreshTip.setAnchorLocation(AnchorLocation.WINDOW_TOP_LEFT)
manualRefreshButton.setTooltip(refreshTip);

var exportButton = new MenuButton(null, new FontIcon(BootstrapIcons.BOX_ARROW_UP));
exportButton.getStyleClass().addAll(Styles.BUTTON_ICON, Tweaks.NO_ARROW);
var exportTip = new Tooltip("This is a MenuButton with styleClass().addAll(Styles.BUTTON_ICON, Tweaks.NO_ARROW)");
exportTip.setAnchorLocation(AnchorLocation.WINDOW_TOP_LEFT);
exportButton.setTooltip(exportTip);

var toolbar = new ToolBar(showHiddenFilesButton, manualRefreshButton, exportButton);
```

**Comment by xiongchun** [comment]
<img width="383" alt="image" src="https://github.com/mkpaz/atlantafx/assets/4091000/447030c1-4374-42d9-a2b3-d0e9fa3eb9a5">

this is my style.
`settingsMenuBtn.getStyleClass().addAll(Tweaks.NO_ARROW);`

**Comment by sillydan1** [comment]
Interesting :thinking: it seems that `Styles.BUTTON_ICON` is to blame here. If I remove that, it seems to work perfectly! Thanks for the hint @xiongchun !
