### ISSUE TITLE
Samples only change by clicking on them, not via selection model.

### ISSUE THREAD

**Issue by dlemmermann** [mkpaz/atlantafx#9]
I used the arrow up and down keys to activate different samples and noticed that nothing happens. It seems like you are listening to mouse clicks and not to selection model events of the left-hand side ListView.

**Comment by mkpaz** [comment]
Yes, that's correct. Sidebar doesn't support keyboard navigation for the moment.

**Comment by mkpaz** [comment]
Fixed with https://github.com/mkpaz/atlantafx/commit/978577dc6a9a785e72241e3d8b3d9a48c2fab6a1
