### ISSUE TITLE
Error running atlantafx in IntelliJ: stack - java: module not found: atlantafx.base

### ISSUE THREAD

**Issue by podwesley** [mkpaz/atlantafx#92]
### Discussed in https://github.com/mkpaz/atlantafx/discussions/91

<div type='discussions-op-text'>

<sup>Originally posted by **podwesley** April 24, 2024</sup>

Hello everyone! I'm encountering an error while running atlantafx on IntelliJ. After adding the dependency in Maven and in the runner, the console shows the following error: java: module not found: atlantafx.base

Does anyone have any idea what this could be? See the image below:
![image](https://github.com/mkpaz/atlantafx/assets/29009797/b4cb656c-0408-44cd-b35d-0c11c4a32849)

</div>

**Comment by mkpaz** [comment]
I'm sorry but this sort of issues should be asked to StackOverflow or https://www.reddit.com/r/javahelp/.
