### ISSUE TITLE
Question - How to make tabs as in demo image?

### ISSUE THREAD

**Issue by PavelTurk** [mkpaz/atlantafx#96]
Could anyone say how to make these two types of tabs (I need both of them):

![Screenshot from 2024-05-08 15-17-55](https://github.com/mkpaz/atlantafx/assets/10261361/13394eb1-a989-414d-8bb0-e0460e4e53d5)

I tried:

        tab.getStyleClass().add(Styles.BORDER_DEFAULT);
        tab.getStyleClass().add(Styles.BORDERED);

But it didn't hellp.

**Comment by iajn** [comment]
Styles.TABS_FLOATING and Styles.TABS_CLASSIC. The Sampler tool is very useful for checking these things out.
